Move elements inside main tag. Fixes #280
wmcadigital/wmn-design-system pull request #296
Opened 2020-08-18 09:44 UTC by gldgrnt

Moved beta banner, breadcrumbs and feedback loop inside the main landmark tag. Fixes #280

2020-08-18 14:29 UTC, gldgrnt commented
The changes I've made are visible here: [https://deploy-preview-296--wmnetwork.netlify.app/patterns/header-and-footer/](https://deploy-preview-296--wmnetwork.netlify.app/patterns/header-and-footer/).

It does, however, add an extra `<div>` below the `<header>` and `<footer>` components

2020-08-19 07:21 UTC, catiarodriguescosta approved these changes
Seems all good for me!

2020-08-19 08:19 UTC, daylesalmon requested changes
Looking good, just a few changes.

2020-08-19 08:19 UTC, daylesalmon commented on src/wmnds/patterns/header/_header.njk
> +  <div class="wmnds-container">
I think you could wrap these two components with just one "wmnds-container" wrapper.
You could then do an if statement around the master wmnds-container to say "if params.banner OR params.breadcrumbs" and keep your if statements inside to render breadcrumb/banner if available.

2020-08-19 08:19 UTC, daylesalmon commented on src/www/pages/patterns/header-and-footer/index.njk
> +}}
Can you move this example to the top of the page as this is our preferred header that we want people to use.

2020-08-19 09:00 UTC, gldgrnt commented
I've replaced the initial example with the full example. We might need to request some copy for the initial example as it now contains the phase banner and the breadcrumbs.

2020-08-19 13:20 UTC, daylesalmon approved these changes

2020-08-19 13:21 UTC, merged

2020-11-11 15:54 UTC, daylesalmon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.0.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: