Added file upload component
wmcadigital/wmn-design-system pull request #319
Opened 2020-08-19 13:59 UTC by houbly

Fixes #281 

Ignore the change to src/wmnds/components/content-tiles/normal/_normal.scss it should be fine but it was a commit from the previous branch, not sure why it committed again.

2020-08-20 07:08 UTC, gldgrnt requested changes
All good except for one bit of indentation.

2020-08-20 07:08 UTC, gldgrnt commented on src/wmnds/components/form-elements/file-upload/_file-upload.njk
> +        </label>
The indentation of the svg tag might be a bit confusing.

![image](https://user-images.githubusercontent.com/43111519/90727925-f4ad9600-e2bb-11ea-911b-40b3cd6b6586.png)

2020-08-20 11:20 UTC, gldgrnt approved these changes
Yeah, looks great!

2020-08-20 12:46 UTC, catiarodriguescosta approved these changes
Looking good. 👍

2020-08-20 12:46 UTC, merged

2020-11-11 15:54 UTC, daylesalmon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.0.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: