Fix header and footer pattern page accessibility issues
wmcadigital/wmn-design-system pull request #340
Opened 2020-08-24 11:28 UTC by gldgrnt

Managed to fix the issues that AXE and IBM flag for duplicate `<nav>` components. Not sure how to fix the issue with the `h1` in the 'Header with title' as the `h1` needs to be present in the code example. Fixes #283

2020-08-24 12:07 UTC, catiarodriguescosta requested changes
I left some comments. Have a look please. :)

2020-08-24 12:07 UTC, catiarodriguescosta commented on src/www/data.njk.json
> +        },
Why is this in this PR? Isn't it already merged?

2020-08-24 12:07 UTC, catiarodriguescosta commented on src/www/pages/components/file-download/index.njk
> +{% endblock %}
Why is this in this PR? Isn't it already merged?

2020-08-24 12:22 UTC, gldgrnt commented
@catiarodriguescosta No sure why the `file-download` component things are appearing here. I've reset my master branch now

2020-08-24 15:16 UTC, catiarodriguescosta approved these changes
Looks good!

2020-08-24 15:25 UTC, houbly approved these changes

2020-08-25 07:38 UTC, merged

2020-11-11 15:53 UTC, daylesalmon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.0.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: