Add back link to links component.
wmcadigital/wmn-design-system pull request #364
Opened 2020-08-26 13:32 UTC by catiarodriguescosta

It's inside links.

Fixes #354

2020-08-26 13:41 UTC, gldgrnt requested changes
All good except for spacing before component example

2020-08-26 13:41 UTC, gldgrnt commented on src/www/pages/components/links/index.njk
> +{% from "wmnds/components/link/link/_link.njk" import wmndsLink %}
Remove the two `<br>` tags to be consistent with the rest of the page

2020-08-27 07:40 UTC, gldgrnt approved these changes
Looks good to me now

2020-08-27 08:07 UTC, daylesalmon approved these changes

2020-08-27 08:09 UTC, merged

2020-11-11 15:53 UTC, daylesalmon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.0.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: