Cc/feature/question pattern
wmcadigital/wmn-design-system pull request #386
Opened 2020-09-02 08:27 UTC by catiarodriguescosta

Fixes #378

2020-09-02 08:31 UTC, catiarodriguescosta commented on src/wmnds/components/form-elements/input/_input.njk
> +  <input class="wmnds-fe-input{{errorClass}}{{paramClass}}" id="{{id}}" name="{{id}}" type="{{type}}"/>
It's not missing. Right before this, we have a label with the "for" linking it. 👍

2020-09-03 10:56 UTC, daylesalmon commented on src/wmnds/components/form-elements/input/_input.njk
> +  <input class="wmnds-fe-input{{errorClass}}{{paramClass}}" id="{{id}}" name="{{id}}" type="{{type}}"/>
@catiarodriguescosta I think this is a none-issue as accesslint may not be able to understand nunjucks variables.

2020-09-03 11:19 UTC, daylesalmon requested changes
Mainly indentation changes, but looking good so far!

2020-09-03 11:19 UTC, daylesalmon commented on src/wmnds/assets/sass/_utilities.scss
> +}
Same with these, can you add them to utilities page.

2020-09-03 11:19 UTC, daylesalmon commented on src/wmnds/components/form-elements/input/_input.njk
>  {% endmacro %}]
"no newline at end of file"

2020-09-03 11:19 UTC, daylesalmon commented on src/wmnds/components/form-elements/input/_input.scss
>  }
This isn't needed, just wrap the html element with a <div class="wmnds-col-1-2"><input /></div>.

2020-09-03 11:19 UTC, daylesalmon commented on src/wmnds/components/message/summary/_summary.njk
>  {% endmacro %}
End of file needs a blank line.

2020-09-03 11:19 UTC, daylesalmon commented on src/wmnds/components/message/summary/_summary.njk
> +{% elseif params.type === "success-fill-no-icon" %}
Like this addition, can you add it to the https://deploy-preview-386--wmnetwork.netlify.app/components/message/ page.

2020-09-03 11:19 UTC, daylesalmon commented on src/wmnds/components/message/summary/_summary.njk
>  {# Warning #}
Can you check your whitespace on the component preview. For instance: https://deploy-preview-386--wmnetwork.netlify.app/components/message/ "success (fill) whitespace is a bit weird.

2020-09-03 11:19 UTC, daylesalmon commented on src/wmnds/components/message/summary/_summary.scss
> +  // Sucess fill no icon
Typo here, should be "success".

2020-09-03 11:19 UTC, daylesalmon commented on src/wmnds/components/table/_table.njk
>      {%- endfor %}
Looks good, again just check the whitespace in the component preview code snippet.

2020-09-03 11:19 UTC, daylesalmon commented on src/wmnds/patterns/question/confirmation-message/_confirmation-message.njk
> +-}}
Just check the indent in the code preview.

2020-09-03 11:19 UTC, daylesalmon commented on src/wmnds/patterns/question/reference/_reference.njk
> +{% endmacro %}
Check your indenting again.
Also, you are missing the form and fieldset elements like your "form element" pattern.

2020-09-03 11:19 UTC, daylesalmon commented on src/wmnds/patterns/question/summary/_summary.njk
> +{% endmacro %}
Indentation needs fixing in code snippet.

2020-09-03 11:19 UTC, daylesalmon commented on src/www/pages/patterns/question-form/index.njk
> +{% endblock %}
New line needed at end of file.

2020-09-03 11:19 UTC, daylesalmon commented on src/www/pages/patterns/question-form/index.njk
> +    }}
This could perhaps be tidied up with the caller method as mentioned by Gil.

2020-09-03 15:17 UTC, gldgrnt reviewed
I think Dayle mentioned all the things that I was going to say!

2020-09-04 13:20 UTC, daylesalmon requested changes
Almost ready to go.

2020-09-04 13:20 UTC, daylesalmon commented on src/www/pages/patterns/question-form/index.njk
> +<br>You also consent to West Midlands Combined Authority reinstating your Direct Debit instruction.</p>",
Can you just indent this so it looks a bit neater... 
I'm working on a separate branch for getting the indentation in code previews etc. to work correctly.

2020-09-04 13:20 UTC, daylesalmon commented on src/www/pages/styles/utility-classes/index.njk
> +  <code class="scss" tabindex="0">
```suggestion
  <code class="wmnds-show-more-ignore scss" tabindex="0">
```

Adding this class stops the "show more code" bottom from appearing.

I've also noticed this is happening on the "containers" code preview on this page. Can you also add the same class to the code preview too.

2020-09-04 14:53 UTC, gldgrnt submitted a review, later dismissed
Other than the changes Dayle suggested, it looks all good to me, good work on all the indentation stuff

2020-09-04 14:56 UTC, gldgrnt reviewed
> Other than the changes Dayle suggested, it looks all good to me, good work on all the indentation stuff

Same as this, but I didn't mean to approve it before !

2020-09-07 09:10 UTC, daylesalmon requested changes
One last change and it should be ready to go live.

2020-09-07 09:10 UTC, daylesalmon commented on src/www/pages/styles/utility-classes/index.njk
> +    .bg-transparent
Can you update the bg names to the same colour names on the [colour palettes page](https://deploy-preview-386--wmnetwork.netlify.app/styles/colour-palettes/) so they are in sync.

An example is changing bg-yellow to bg-planned-disruption.

2020-09-07 13:44 UTC, gldgrnt approved these changes
Looks all good to me

2020-09-07 15:23 UTC, daylesalmon approved these changes

2020-09-07 15:25 UTC, merged

2020-11-11 15:52 UTC, daylesalmon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.0.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: