Add Emergency banner
wmcadigital/wmn-design-system pull request #401
Opened 2020-09-11 08:11 UTC by gldgrnt

I'm not 100% convinced this is the best way to do this, so let me know if you know of a better way. Fixes #395

2020-09-11 10:12 UTC, daylesalmon requested changes
A few minor changes and it's ready to go.

2020-09-11 10:12 UTC, daylesalmon commented on src/wmnds/assets/sass/_vars.scss
> +  emergency: #231f20
I think this is the same colour as the "text" var.
Just update to use the text colour instead and remove this one.

2020-09-11 10:12 UTC, daylesalmon commented on src/wmnds/patterns/banner/_banner.scss
> +    background-color: get-color(emergency);
Change background colour to "text" as mentioned earlier.

2020-09-11 11:08 UTC, houbly approved these changes

2020-09-14 09:36 UTC, catiarodriguescosta approved these changes
Looks pretty good to me!

2020-09-14 09:39 UTC, houbly approved these changes

2020-09-15 12:46 UTC, daylesalmon approved these changes

2020-09-15 12:52 UTC, merged

2020-11-11 15:52 UTC, daylesalmon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.0.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: