Add indentation for long list content
wmcadigital/wmn-design-system pull request #424
Opened 2020-09-24 08:38 UTC by gldgrnt

Fixes #423

2020-09-24 12:25 UTC, houbly approved these changes

2020-09-28 07:36 UTC, catiarodriguescosta requested changes
https://deploy-preview-424--wmnetwork.netlify.app/components/lists/ something is not right.... we need a different solution to fix https://github.com/wmcadigital/wmn-design-system/issues/423.

2020-09-28 08:44 UTC, gldgrnt commented
> https://deploy-preview-424--wmnetwork.netlify.app/components/lists/ something is not right.... we need a different solution to fix #423 

Wow yeah that's not nice, will fix!

2020-09-28 13:09 UTC, gldgrnt commented
I've fixed the issue with the ordered lists and noticed that both ordered and unordered were missing some vertical spacing that was present in the design.

2020-09-29 10:51 UTC, daylesalmon requested changes

2020-09-29 10:51 UTC, daylesalmon commented on src/wmnds/components/lists/ordered-list/_ordered-list.scss
Can you add some padding-inline-start to this like there is on the child ol/ul elements. 

The reason I ask, is that currently the padding on the root ul/ol element comes from the user-agent (browser) styling.
And as you are doing some negative left stuff below, we want to make sure that no matter the browser there is enough space that the negative left can fall into.

An example is, what if a browser treats ul/ol's as having 0 padding-inline-start, then your -1.5rem left will make the bullet icon appear outside of the element/design.

This is the current user-agent styling in chrome as an example:
![image](https://user-images.githubusercontent.com/13015201/94549385-0a629380-024a-11eb-9efa-726e28b83eb3.png)

2020-09-29 10:51 UTC, daylesalmon commented on src/wmnds/components/lists/unordered-list/_unordered-list.scss
>  }
Again in this file...

Can you add some padding-inline-start to this like there is on the child ol/ul elements. 

The reason I ask, is that currently the padding on the root ul/ol element comes from the user-agent (browser) styling.
And as you are doing some negative left stuff below, we want to make sure that no matter the browser there is enough space that the negative left can fall into.

An example is, what if a browser treats ul/ol's as having 0 padding-inline-start, then your -1.5rem left will make the bullet icon appear outside of the element/design.

This is the current user-agent styling in chrome as an example:
![image](https://user-images.githubusercontent.com/13015201/94549385-0a629380-024a-11eb-9efa-726e28b83eb3.png)

2020-09-30 07:33 UTC, catiarodriguescosta approved these changes
Looks good!

2020-09-30 12:58 UTC, daylesalmon approved these changes

2020-09-30 12:59 UTC, merged

2020-11-11 15:51 UTC, daylesalmon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.0.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: