Added new search pattern components
wmcadigital/wmn-design-system pull request #455
Opened 2020-10-19 11:17 UTC by houbly

Includes: 
- Search bar
- Sort
- Filter
- Search result
- Pagination

2020-10-19 13:43 UTC, gldgrnt reviewed
All looks good to me. Just wondering if it's worth using `wmndsIcon()` macro in the .njk files just in case the icons get updated in future.

2020-10-20 08:25 UTC, catiarodriguescosta requested changes
Didn't have time to dig, but it looks pretty well. 
Just left a tiny suggestion - that could not make sense in this particular case.

2020-10-20 08:25 UTC, catiarodriguescosta commented on src/wmnds/patterns/search/search-filter/_search-filter.scss
> +        font-size: 1.4375rem;
Can't we round it?

2020-10-22 10:31 UTC, houbly commented on src/wmnds/patterns/search/search-filter/_search-filter.scss
> +        font-size: 1.4375rem;
Sure. I have no Idea how that got there

2020-10-28 08:35 UTC, catiarodriguescosta approved these changes
Looks good to me! 👍

2020-11-02 14:35 UTC, jkmnch approved these changes

2020-11-04 09:43 UTC, gldgrnt approved these changes
Looks good!

2020-11-05 11:10 UTC, merged

2020-11-11 15:51 UTC, daylesalmon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.0.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: