Message: Fix behaviour when title is big.
wmcadigital/wmn-design-system pull request #488
Opened 2020-11-09 15:28 UTC by catiarodriguescosta

2020-11-10 09:38 UTC, gldgrnt requested changes
All look good, except for the inlining of all the njk imports

2020-11-10 10:11 UTC, daylesalmon requested changes
A few changes are needed before this can be pulled in.
We shouldn't be using grid classes within a component, as that introduces too much flexibility and is more prone to broken components. 
Grid classes should only be used on patterns as they are meant to be more fluid/flexible.

2020-11-10 10:11 UTC, daylesalmon commented on src/wmnds/components/message/summary/_summary.njk
> +from "wmnds/components/icon/_icon.njk" import wmndsIcon %}
Undo the inlining for this.

2020-11-10 10:11 UTC, daylesalmon commented on src/wmnds/components/message/summary/_summary.njk
> +  <div class="wmnds-msg-summary__header wmnds-grid">
We shouldn't be using the wmnds-grid on components. It should only be used within patterns.

2020-11-10 10:11 UTC, daylesalmon commented on src/wmnds/components/message/summary/_summary.njk
> +    <h3 class="wmnds-msg-summary__title wmnds-col-1">{{ params.title }}</h3>
Again wmnds-col-1 shouldn't be used in components. Only should be in patterns.

2020-11-10 10:11 UTC, daylesalmon commented on src/wmnds/components/message/summary/_summary.scss
>    }
Have you confirmed this works in older IE (IE11)?

2020-11-10 11:44 UTC, houbly approved these changes

2020-11-11 08:52 UTC, daylesalmon approved these changes

2020-11-11 08:52 UTC, merged

2020-11-11 15:50 UTC, daylesalmon commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.0.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: