Mega menu header and search bug fixes
wmcadigital/wmn-design-system pull request #492
Opened 2020-11-12 15:31 UTC by houbly

Fixes #462 
- Put search links in 2 columns to allow vertical tab direction
- Removed h1 tag from search, replaced with h1 class
- Updated search section to show correct breadcrumbs and patterns sidebar instead of components sidebar
- Refactored nav functions to allow keyboard navigation within search list

2020-11-19 13:25 UTC, jkmnch submitted a review, later dismissed

2020-11-19 13:42 UTC, gldgrnt requested changes
The base of this PR needs to be changed to the `release` branch (can be done by clicking edit at the top).

Other than that everything looks good!

2020-11-20 09:05 UTC, jkmnch approved these changes

2020-11-20 11:35 UTC, gldgrnt approved these changes
👍🏾

2020-11-30 10:49 UTC, jkmnch approved these changes

2020-11-30 12:06 UTC, merged

2020-12-01 12:59 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.1.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: