feat: updated component example look and feel
wmcadigital/wmn-design-system pull request #506
Opened 2020-11-27 15:40 UTC by daylesalmon

feat: Component examples now support displaying components in iframes
feat: Component examples can now show njk snippets and properties
feat: Component example can be scaled by dragging with mouse

2020-11-30 09:07 UTC, catiarodriguescosta requested changes
Great work here @daylesalmon. 
The things I could identify were components that appeared empty: 
- the Mobile app variant of Footer on [this page](https://deploy-preview-506--wmnetwork.netlify.app/patterns/header-and-footer/)
- the cookie banner on [this pahe](https://deploy-preview-506--wmnetwork.netlify.app/patterns/cookies/)

Also, indentation inside HTML looks weird, but I guess that is a non-issue for this PR.

2020-11-30 09:10 UTC, gldgrnt requested changes
Great! Just a few incredibly minor things 👍🏾

2020-11-30 09:10 UTC, gldgrnt commented on package.json
> +    "gulp": "^4.0.2",
Should this be a dev dependency?

2020-11-30 09:10 UTC, gldgrnt commented on debug.log
> +[1126/091032.579:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
This should probably be deleted / added to .gitignore

2020-11-30 16:01 UTC, daylesalmon commented on package.json
> +    "gulp": "^4.0.2",
Yup!

2020-11-30 16:41 UTC, daylesalmon commented
> Great work here @daylesalmon.
> The things I could identify were components that appeared empty:
> 
> * the Mobile app variant of Footer on [this page](https://deploy-preview-506--wmnetwork.netlify.app/patterns/header-and-footer/)
> * the cookie banner on [this pahe](https://deploy-preview-506--wmnetwork.netlify.app/patterns/cookies/)
> 
> Also, indentation inside HTML looks weird, but I guess that is a non-issue for this PR.

I've fixed the mobile app variant...As the pattern is display:none on mobile devices and it is displayed in an iframe within the column it treated it as if it was mobile so wasn't showing anything (even though the HTML is there).
As a quick fix i've just took it out of the iframe so something shows.

The cookie issue...Looks as though this was already an issue on the live design system. I'll have a look and implement a fix.

2020-12-01 10:24 UTC, gldgrnt approved these changes
Looks really good to me! 👍🏾

2020-12-01 11:31 UTC, catiarodriguescosta approved these changes
Looks pretty good to me! 👍

2020-12-01 11:32 UTC, merged

2020-12-01 12:59 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.1.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: