add markdown
wmcadigital/wmn-design-system pull request #540
Opened 2020-12-17 16:46 UTC by houbly

2021-01-13 12:05 UTC, catiarodriguescosta requested changes
Just a tiny tiny details. Nothing to say about anything else. Really good work here! 👍

2021-01-13 12:05 UTC, catiarodriguescosta commented on src/wmnds/patterns/question/summary/_summary.njk
>              }) | trim | indent(4)
```suggestion
            })
```

2021-01-13 12:05 UTC, catiarodriguescosta commented on src/wmnds/patterns/question/summary/_summary.njk
>              }) | trim | indent(4),
```suggestion
            })
```

2021-01-13 12:05 UTC, catiarodriguescosta commented on src/wmnds/components/table/_table.njk
>    {% endif -%}
```suggestion
  {% endif %}
```

2021-01-13 12:05 UTC, catiarodriguescosta commented on src/wmnds/components/table/_table.njk
>    {%- endif -%}
```suggestion
  {% endif %}
```

2021-01-13 13:21 UTC, catiarodriguescosta approved these changes
Looking good! 👍

2021-01-14 09:27 UTC, daylesalmon commented
Can't review as the PR preview is breaking: https://github.com/wmcadigital/wmn-design-system/pull/540/checks?check_run_id=1700674653 

If you fix that i'll have a look.

2021-01-14 12:18 UTC, daylesalmon requested changes
Just a few changes. But really good work, this looks like it would of been quite complex!

2021-01-14 12:18 UTC, daylesalmon commented on src/wmnds/components/table/_properties.njk.json
> +{
Make sure all of these are in the same order as the example for consistency.
For example, title is above caption in the example and head is above rows.

2021-01-14 12:18 UTC, daylesalmon commented on src/wmnds/patterns/question/summary/_summary.njk
> +                            contentText: "Cell",
Can you make the last cell a button as link with the text "Change" like how it would be in a live form.

Do this for all last cells.

2021-01-14 14:59 UTC, daylesalmon requested changes
One minor change and it's ready to go!

2021-01-14 14:59 UTC, daylesalmon commented on src/wmnds/patterns/question/summary/_summary.njk
> +                            contentHTML: "<a href='#'>Change</a>",
```suggestion
                            contentHTML: "<button type="button" class="wmnds-btn wmnds-btn--link ">Change</button>",
```

Change all of these to buttons like above.

2021-01-18 09:41 UTC, daylesalmon approved these changes

2021-01-18 09:47 UTC, merged

2021-01-20 16:04 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.2.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: