feat: message documentation
wmcadigital/wmn-design-system pull request #554
Opened 2020-12-23 08:57 UTC by houbly

2021-01-13 11:35 UTC, catiarodriguescosta requested changes
Left a few notes! 👍

2021-01-13 11:35 UTC, catiarodriguescosta commented on src/wmnds/components/message/summary/_properties.njk.json
> +      "description": "Type of the button. As default it is <code class='wmnds-website-inline-code'>null</code>. Available types: <code class='wmnds-website-inline-code'>link</code>, <code class='wmnd
Wrong description

2021-01-13 11:35 UTC, catiarodriguescosta commented on src/wmnds/components/message/summary/_properties.njk.json
> +      "description": "Type of the button. As default it is <code class='wmnds-website-inline-code'>null</code>. Available types: <code class='wmnds-website-inline-code'>link</code>, <code class='wmnd
Wrong description

2021-01-13 15:06 UTC, catiarodriguescosta approved these changes
Just found those two tiny indentation things. Will approve it anyway! 👍

2021-01-13 15:06 UTC, catiarodriguescosta commented on src/wmnds/patterns/content-cards/travel-updates/_travel-updates.njk
>              }) | indent(12) | trim
```suggestion
            })
```

2021-01-13 15:06 UTC, catiarodriguescosta commented on src/wmnds/patterns/question/confirmation-message/_confirmation-message.njk
>      }) | trim
```suggestion
    })
```

2021-01-14 10:15 UTC, daylesalmon requested changes
Just a few changes.

2021-01-14 14:49 UTC, daylesalmon approved these changes

2021-01-14 14:52 UTC, merged

2021-01-20 16:04 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.2.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: