fix: modifed content card styles to meet WCAG 2.1 AA
wmcadigital/wmn-design-system pull request #586
Opened 2021-01-08 15:56 UTC by houbly

fixes #549

2021-01-12 14:48 UTC, catiarodriguescosta approved these changes
👍

2021-01-14 12:34 UTC, daylesalmon requested changes

2021-01-14 12:34 UTC, daylesalmon commented on src/wmnds/components/content-card/_content-card.scss
> +    text-decoration: underline;
This should only happen when hovered according to: https://github.com/wmcadigital/wmn-design-system/issues/549#issuecomment-753901729

2021-01-14 13:03 UTC, daylesalmon approved these changes

2021-01-14 13:04 UTC, daylesalmon commented on src/wmnds/components/content-card/_content-card.scss
> +    text-decoration: underline;
None-issue...Resolved by speaking with @houbly.

2021-01-14 13:04 UTC, merged

2021-01-20 16:04 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.2.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: