feat: lists documentation
wmcadigital/wmn-design-system pull request #589
Opened 2021-01-13 13:13 UTC by houbly

- move list documentation from components section to styles section
- added markdown and updated examples for lists

2021-01-13 15:37 UTC, catiarodriguescosta submitted a review, later dismissed
Looking good! 👍

2021-01-14 09:23 UTC, daylesalmon requested changes
As we are not using the import njk macro file anymore, as this is now a style...

Can you delete the macro njk files (components/lists/_(ordererd-list.njk | unordered-list.njk).

Then can you move the scss files for each into src/wmnds/assets/sass folder.
Finally, can you add a subfolder in the sass folder called "styles" with a file called styles.scss and add anything into the subfolder and import into the styles.scss that is on the styles pages, i.e. typography.scss, utilities.scss

2021-01-14 14:27 UTC, daylesalmon approved these changes

2021-01-14 14:38 UTC, merged

2021-01-20 16:04 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.2.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: