fix: add linkTitle param and rename href to link
wmcadigital/wmn-design-system pull request #591
Opened 2021-01-14 13:27 UTC by catiarodriguescosta

- Rename href param to link
- Add new linkTitle param
- Fixes  #528

2021-01-14 16:30 UTC, daylesalmon requested changes
A few changes and it's ready to go.

2021-01-14 16:30 UTC, daylesalmon commented on src/wmnds/components/content-card/_content-card.njk
> +{% set tag = "a" if params.link else "div" %}
```suggestion
{% set _tag = "a" if params.link else "div" %}
```

This is just an internal var based on a param, so underscore and drop next to _attributes below.

2021-01-14 16:30 UTC, daylesalmon commented on src/wmnds/components/content-card/_example.njk
>        yellow: false,
Drop this below classes so that it matches the order of the nunjuck properties in the json

2021-01-14 16:30 UTC, daylesalmon commented on src/wmnds/components/content-card/_example.njk
> +      link: "https://designsystem.wmnetwork.co.uk/components/content-card/",
contentHTML is missing too.

2021-01-15 09:35 UTC, houbly approved these changes

2021-01-15 11:12 UTC, daylesalmon approved these changes

2021-01-15 11:24 UTC, merged

2021-01-20 16:04 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.2.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: