feat: page banner component
wmcadigital/wmn-design-system pull request #612
Opened 2021-01-22 08:54 UTC by houbly

- Added new page banner component page with responsive travel mode page banner
- Added component props and examples

fixes #520

2021-01-22 09:15 UTC, jkmnch reviewed
Ideally, this new banner pattern should go under the Banner section of the Patterns page. Is there a reason why this was changed?

2021-01-22 13:43 UTC, mrmjprice requested changes
## Mode values:
- [ ] Add cycling
- [x] Add walking
- [ ] Add none

If mode not specified, default to primary colour with no icon.

2021-01-25 15:50 UTC, houbly commented
> Ideally, this new banner pattern should go under the Banner section of the Patterns page. Is there a reason why this was changed?

My bad. I don't think it was specified and it seemed like a separate component to banner. I've moved it to the banner page now.

2021-01-25 15:55 UTC, jkmnch approved these changes

2021-01-27 08:21 UTC, mrmjprice approved these changes

2021-01-27 10:19 UTC, daylesalmon requested changes

2021-01-27 10:19 UTC, daylesalmon commented on src/wmnds/patterns/page-banner/_example.njk
> +    logoAltText: "West Midlands Bus"
Going to remove these two fields and put them within the pattern.

2021-01-27 12:03 UTC, daylesalmon approved these changes

2021-01-27 12:05 UTC, merged

2021-01-29 12:42 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.3.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: