fix: style update on travel mode banner
wmcadigital/wmn-design-system pull request #699
Opened 2021-03-18 13:02 UTC by catiarodriguescosta

- min-height on desktop of 300px
- logos are now aligned to the bottom of the banner.

2021-03-18 15:47 UTC, daylesalmon requested changes
It looks good, but can you use browserstack to check and fix the issues in IE11. 
It currently looks like:

![image](https://user-images.githubusercontent.com/13015201/111655087-4215c580-8801-11eb-9315-0fceb21e9b7e.png)

2021-04-06 09:03 UTC, gldgrnt approved these changes
👍🏾

2021-04-06 10:14 UTC, houbly approved these changes

2021-04-07 09:22 UTC, daylesalmon approved these changes

2021-04-07 09:22 UTC, merged

2021-04-12 10:38 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.5.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: