Add feedback loop functionality
wmcadigital/wmn-design-system pull request #714
Opened 2021-03-31 13:48 UTC by gldgrnt

Addressing the requirements in [this issue](https://github.com/wmcadigital/wmn-sprints/issues/22).

2021-04-09 14:37 UTC, daylesalmon submitted a review, later dismissed
Fantastic work on this @gldgrnt! 🥳 

It looks good and seems to be working. Is this linked to the live API? (ready to be used elsewhere as is?)

2021-04-12 08:26 UTC, catiarodriguescosta requested changes
Looks good! 👍 Just found some typos!

2021-04-12 08:26 UTC, catiarodriguescosta commented on src/wmnds/patterns/feedback-loop/_properties.njk.json
> +          "description": "HTMl shown once 'Is this page useful?' feedback is submitted. If <code class='wmnds-website-inline-code'>contentHTML</code> is provided, the <code class='wmnds-website-inlin
```suggestion
        {
          "name": "contentHTML",
          "type": "string",
          "description": "HTML shown once 'Is this page useful?' feedback is submitted. If <code class='wmnds-website-inline-code'>contentHTML</code> is provided, the <code class='wmnds-website-inline-code'>contentText</code> argument will be ignored."
```

2021-04-12 08:26 UTC, catiarodriguescosta commented on src/wmnds/patterns/footer/_footer.njk
>      }) | trim | indent(4)
```suggestion
    })
```

2021-04-12 08:26 UTC, catiarodriguescosta commented on src/wmnds/patterns/feedback-loop/_example.js
> +  };
```suggestion
  const createErrorMessage = textContent => {
    const element = document.createElement('span');
    element.classList.add(errorMessageClass);
    element.textContent = textContent;
    return element;
  };
```

2021-04-12 08:26 UTC, catiarodriguescosta commented on src/wmnds/patterns/feedback-loop/_properties.njk.json
> +          "description": "<strong>Required</strong> HTMl to be used in the input label. If <code class='wmnds-website-inline-code'>labelHTML</code> is provided, <code class='wmnds-website-inline-code
```suggestion
          "description": "<strong>Required</strong> HTML to be used in the input label. If <code class='wmnds-website-inline-code'>labelHTML</code> is provided, <code class='wmnds-website-inline-code'>labelText</code> will be ignored."
```

2021-04-12 09:12 UTC, catiarodriguescosta approved these changes
👍

2021-04-12 09:13 UTC, daylesalmon approved these changes

2021-04-12 09:17 UTC, merged

2021-04-12 10:38 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.5.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: