feat: Added new 'create a short url' page
wmcadigital/wmn-design-system pull request #727
Opened 2021-04-09 08:10 UTC by houbly

Added new 'create a short url' page
Fixes #681

2021-04-09 08:14 UTC, mrmjprice requested changes
Can we rename the page to: ```Friendly links (short URLs)```

2021-04-09 08:19 UTC, daylesalmon commented
@houbly - Will review after the change mentioned by @mrmjprice.

2021-04-09 12:15 UTC, mrmjprice approved these changes

2021-04-09 14:31 UTC, daylesalmon approved these changes

2021-04-09 14:31 UTC, merged

2021-04-12 10:38 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.5.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: