feat: Adding a new page about seo.
wmcadigital/wmn-design-system pull request #737
Opened 2021-04-19 08:40 UTC by catiarodriguescosta

Fixes #682

2021-04-20 09:15 UTC, gldgrnt requested changes
All good except for 1 typo! 👍🏾

2021-04-20 09:15 UTC, gldgrnt commented on src/www/pages/styles/seo/index.njk.md
> +- [An SEO drescription](https://yoast.com/meta-descriptions/), the description of the page for search engines
Typo of 'description' here

2021-04-22 10:02 UTC, gldgrnt approved these changes
Nice nice nice

2021-04-26 07:47 UTC, houbly approved these changes

2021-04-26 07:48 UTC, merged

2021-05-05 12:12 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.6.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: