feat: add DM Sans Regular
wmcadigital/wmn-design-system pull request #748
Opened 2021-04-27 07:53 UTC by houbly

fixes #747

2021-04-27 08:14 UTC, gldgrnt submitted a review, later dismissed
👍🏾

2021-04-29 09:37 UTC, gldgrnt requested changes
All looks good except for one typo!

2021-04-29 09:37 UTC, gldgrnt commented on src/www/pages/styles/typography/index.njk.md
> +We utilise <a href="https://fonts.google.com/" target="_blank">Google Fonts</a> in our typography and all fonts used are pre-bundled in our design system CSS, so you won't need to include them sepera
Just this typo:

```suggestion
We utilise <a href="https://fonts.google.com/" target="_blank">Google Fonts</a> in our typography and all fonts used are pre-bundled in our design system CSS, so you won't need to include them separately.
```

2021-04-29 09:43 UTC, gldgrnt approved these changes
👍🏾

2021-04-29 10:23 UTC, catiarodriguescosta approved these changes
👍

2021-04-29 10:31 UTC, merged

2021-05-05 12:12 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.6.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: