feat: find timetable pattern
wmcadigital/wmn-design-system pull request #771
Opened 2021-05-10 14:39 UTC by catiarodriguescosta

**NOT READY FOR REVIEW YET**

Fixes #760

2021-05-11 10:17 UTC, mrmjprice requested changes
Please can you find a replace ```Find timetable``` and replace it with ```Find a timetable``` to add an 'a'? Thank you.

2021-05-14 13:22 UTC, gldgrnt requested changes
All good with markup/styles, but title and page link are 'Find ticket' instead of 'Find a ticket' (and this causes a 404 when you click the link in the navigation or sidebar)

2021-05-14 13:22 UTC, gldgrnt commented on src/www/data.njk.json
> +        },
```suggestion
        {
          "name": "Find a timetable"
        },
```

2021-05-14 13:22 UTC, gldgrnt commented on src/wmnds/patterns/find-a-timetable-widget/_find-a-timetable-widget.njk
> +{% set formTitle = params.formTitle if params.formTitle else "Find timetable" %}
```suggestion
{% set formTitle = params.formTitle if params.formTitle else "Find a timetable" %}
```

2021-05-14 13:22 UTC, gldgrnt commented on .vscode/settings.json
> +  "peacock.color": "#1857a4"
Not sure if this should be committed (?)

2021-05-17 09:18 UTC, houbly approved these changes
Looks good

2021-05-17 09:26 UTC, jkmnch requested changes
The train and tram buttons should be switched, so the order is Bus, Train and Tram.

Also, the 'Anything else' section is just for reference in the GitHub issue and shouldn't be in the DS.

2021-05-17 09:41 UTC, jkmnch requested changes
Sorry, last change! The Train button links to the correct timetables page on the old site, but the Tram button doesn't. Can the Tram button be linked to here? https://www.networkwestmidlands.com/plan-your-journey/timetables/#/?mode=Tram&serviceNo=MM1&limit=6

2021-05-17 09:54 UTC, catiarodriguescosta commented
> Sorry, last change! The Train button links to the correct timetables page on the old site, but the Tram button doesn't. Can the Tram button be linked to here? https://www.networkwestmidlands.com/plan-your-journey/timetables/#/?mode=Tram&serviceNo=MM1&limit=6

No problem Jake, it's fixe now. Thanks for all the checks! :)

2021-05-17 09:58 UTC, jkmnch requested changes
The link doesn't work for me strangely. It reverts back to the default Timetables page when I click on the button. I don't think that link will work. It might have to be changed to this one instead: https://www.networkwestmidlands.com/plan-your-journey/timetables/#/route/cen_01MM1_%20_H_y11_26-26

2021-05-17 10:53 UTC, jkmnch submitted a review, later dismissed
Looks great. Thanks Catia :)

2021-05-19 09:44 UTC, gldgrnt approved these changes
All looks good to me

2021-05-19 10:18 UTC, houbly approved these changes

2021-05-19 10:23 UTC, mrmjprice approved these changes

2021-05-19 10:23 UTC, merged

2021-05-19 12:07 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.7.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.7.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: