feat: add Buy a ticket pattern
wmcadigital/wmn-design-system pull request #778
Opened 2021-05-13 09:43 UTC by gldgrnt

Fixes #759

2021-05-13 09:55 UTC, jkmnch requested changes
Selecting the Train or Tram buttons gives them a purple fill, instead of the standard active button style

2021-05-13 12:51 UTC, catiarodriguescosta requested changes
I left some suggestions that will turn my / Dayle's life easier. :)
But it is looking good! 👍

2021-05-13 12:51 UTC, catiarodriguescosta commented on src/wmnds/patterns/buy-a-ticket/_buy-a-ticket.njk
> +    <div class="wmnds-m-b-md wmnds-p-b-xsm">
```suggestion - I will update form details after
    <form class="wmnds-m-b-md wmnds-p-b-xsm">
```

2021-05-13 12:51 UTC, catiarodriguescosta commented on src/wmnds/patterns/buy-a-ticket/_buy-a-ticket.njk
> +    </div>
```suggestion
    </form>
```

2021-05-13 12:51 UTC, catiarodriguescosta commented on src/wmnds/patterns/buy-a-ticket/_buy-a-ticket.njk
> +                {{
```suggestion
<input type="checkbox" class="wmnds-screenreaders-only" name="useTrain" />
                {{ 
```

2021-05-13 12:51 UTC, catiarodriguescosta commented on src/wmnds/patterns/buy-a-ticket/_buy-a-ticket.njk
> +                {{
```suggestion
<input type="checkbox" class="wmnds-screenreaders-only" name="useBus" />
                {{ 
```

2021-05-13 12:51 UTC, catiarodriguescosta commented on src/wmnds/patterns/buy-a-ticket/_buy-a-ticket.njk
> +                {{
```suggestion
                <input type="checkbox" class="wmnds-screenreaders-only" name="useTram" />
                {{ 
```

2021-05-13 12:51 UTC, catiarodriguescosta commented on src/wmnds/patterns/buy-a-ticket/_buy-a-ticket.njk
> +            id: 'buyATicketTraveller',
If wmndsDropdown accepts name for the input could you add **name: "PassengerType",**, please!

2021-05-13 12:51 UTC, catiarodriguescosta commented on src/wmnds/patterns/buy-a-ticket/_buy-a-ticket.njk
> +            id: "buyATicketDuration",
same here: **name: "Duration",**

2021-05-13 12:51 UTC, catiarodriguescosta commented on src/wmnds/patterns/buy-a-ticket/_buy-a-ticket.njk
> +            contentText: "Find tickets"
```suggestion
            contentText: "Find tickets",
            role: "submit"
```

2021-05-13 13:25 UTC, jkmnch approved these changes

2021-05-13 14:58 UTC, catiarodriguescosta approved these changes
Looks good to me! 👍

2021-05-14 07:35 UTC, merged

2021-05-19 12:08 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.7.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.7.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: