feat: add Swift Content Card
wmcadigital/wmn-design-system pull request #779
Opened 2021-05-13 14:03 UTC by houbly

fixes #777

2021-05-13 14:19 UTC, gldgrnt requested changes
Looks good but is missing the 'When not to use it?' section. Also added bullet point suggestion to keep the content consistent with the rest of the page.

2021-05-13 14:19 UTC, gldgrnt commented on src/www/pages/patterns/content-cards/index.njk.md
> +Shows the image of Swift card and explains how to purchase it
```suggestion
- Shows the image of Swift card and explains how to purchase it
```

2021-05-13 14:19 UTC, gldgrnt commented on src/www/pages/patterns/content-cards/index.njk.md
> +Only on Swift product landing pages such as Swift Go and PAYG
```suggestion
- Only on Swift product landing pages such as Swift Go and PAYG
```

2021-05-14 07:49 UTC, KaterinaKir approved these changes
Looks good to me.

2021-05-14 07:59 UTC, gldgrnt approved these changes
👍🏾

2021-05-14 08:36 UTC, merged

2021-05-14 09:51 UTC, mrmjprice commented
https://github.com/wmcadigital/wmn-cms/issues/114

2021-05-19 12:08 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.7.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.7.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: