feat: add journey planner pattern and update pattern page
wmcadigital/wmn-design-system pull request #781
Opened 2021-05-14 09:25 UTC by catiarodriguescosta

** Please approve first, the bugfixes applied to journey planner widget. After that PR is merged we need to rebase this one and it will be ready to approve. **

2021-05-17 13:12 UTC, jkmnch requested changes
The Plan your journey CTA on the collapsed view is linked to the journey planner. I don't think we need to link the button for this component since it's quite obvious what the button does, so the link can be removed.

In the expanded view, the active state of the travel mode buttons isn't showing correctly. Instead, it gives them a purple fill which hides the icons and text.

Also, do you think you can make the Switch icon white? It does pass colour contrast with secondary purple, but looking at it in the DS has made me think it would be safer in white.

2021-05-17 14:01 UTC, jkmnch approved these changes

2021-05-17 14:20 UTC, houbly approved these changes

2021-05-17 14:20 UTC, merged

2021-05-19 12:07 UTC, wmcadigital-admin commented
:tada: This PR is included in version 1.7.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/wmn-design-system/v/1.7.0)
- [GitHub release](https://github.com/wmcadigital/wmn-design-system/releases/tag/v1.7.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: